### ISSUE TITLE
User "Username" was not found

### ISSUE THREAD

**Issue by Le10E** [pgrimaud/lametric-fortnite#1]
Trying the Fortnite ticker, I have both PS4 and XBOX1 accounts used on Fortnite. I have tried both of them in the App and both of them come up as "User <Username> was not found".    I have repeatedly checked the user names and tried upper, mixed and lower case. Neither of them work. Is there something that I need to enable?

**Comment by pgrimaud** [comment]
Hi, what's your Username ?

**Comment by Le10E** [comment]
AitkenNick on both platforms

**Comment by Le10E** [comment]
This shows the stats correctly
https://fortnitetracker.com/profile/psn/psn(aitkennick)
so does this
https://fortnitetracker.com/profile/xbox/xbl(aitkennick)

**Comment by pgrimaud** [comment]
That's weird...

I can't find any player named 'AitkenNick', take a look at it here : https://fortnitetracker.com/profile/search?q=AitkenNick

But, your profile is available here https://fortnitetracker.com/profile/pc/psn(AitkenNick), with PSN or Xbox account.

Did you linked your PSN ID and Gamertag to an EPIC account ?

**Comment by Le10E** [comment]
OK, I re-did it all and it's now there and the app is now working. Sorry
for wasting your time

**Comment by pgrimaud** [comment]
No problem 😄
