### ISSUE TITLE
"400 Bad Request"

### ISSUE THREAD

**Issue by OneGaming36** [pgrimaud/lametric-fortnite#2]
Hey,

I get the following error when trying to retrieve my user data:
"CLIENT ERROR: 'POST HTTPS://ACCOUNT-PUBLIC-SERVICE-PROD03.OL.EPICGAMES.COM/ACCOUNT/API/OAUTH/TOKEN' RESULTED IN A '400 BAD REQUEST' RESPONSE"
and
"SORRY YOUR CLIENT IS NOT TRUNCATED"

Seems like the client is not autorized.
The whole error text is a little longer, but I think thats all the necessary information.

**Comment by pgrimaud** [comment]
Hello,

Sorry about the delay.

I just fixed the app.

Pierre

**Comment by OneGaming36** [comment]
Thank you, it works fine now!
